/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;


import com.incloud.hcp.domain._framework.BaseDomain;
import com.incloud.hcp.domain._framework.Identifiable;
import com.incloud.hcp.validation.FixedLength;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.Date;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;
import static javax.persistence.TemporalType.TIMESTAMP;

@Entity
@Table(name = "pp_app_proceso_log")
public class AppProcesoLog extends BaseDomain implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(AppProcesoLog.class.getName());

    // Raw attributes
    private Integer id;
    private Date fechaInicioEjecucion;
    private Date fechaFinEjecucion;
    private String estadoEjecucion;
    private String descripcionEstadoEjecucion;
    private String claseProgramacion;
    private String metodoProgramacion;
    private String parametroEntrada;
    private String resultadoSalida;
    private String usuario;
    private Long duracionMs;
    private String ancara;

    @Override
    public String entityClassName() {
        return AppProcesoLog.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "id_app_proceso_log", precision = 10)
    @GeneratedValue(strategy = SEQUENCE, generator = "pp_seq_app_proceso_log")
    @Id
    @SequenceGenerator(name = "pp_seq_app_proceso_log", sequenceName = "pp_seq_app_proceso_log", allocationSize = 1)
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public AppProcesoLog id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [fechaInicioEjecucion] ------------------------

    @NotNull
    @Column(name = "fecha_inicio_ejecucion", nullable = false, length = 29)
    @Temporal(TIMESTAMP)
    public Date getFechaInicioEjecucion() {
        return fechaInicioEjecucion;
    }

    public void setFechaInicioEjecucion(Date fechaInicioEjecucion) {
        this.fechaInicioEjecucion = fechaInicioEjecucion;
    }

    public AppProcesoLog fechaInicioEjecucion(Date fechaInicioEjecucion) {
        setFechaInicioEjecucion(fechaInicioEjecucion);
        return this;
    }
    // -- [fechaFinEjecucion] ------------------------

    @NotNull
    @Column(name = "fecha_fin_ejecucion", nullable = false, length = 29)
    @Temporal(TIMESTAMP)
    public Date getFechaFinEjecucion() {
        return fechaFinEjecucion;
    }

    public void setFechaFinEjecucion(Date fechaFinEjecucion) {
        this.fechaFinEjecucion = fechaFinEjecucion;
    }

    public AppProcesoLog fechaFinEjecucion(Date fechaFinEjecucion) {
        setFechaFinEjecucion(fechaFinEjecucion);
        return this;
    }
    // -- [estadoEjecucion] ------------------------

    @FixedLength(length = 1, nullable = false)
    @NotEmpty
    @Column(name = "estado_ejecucion", nullable = false, length = 1)
    public String getEstadoEjecucion() {
        return estadoEjecucion;
    }

    public void setEstadoEjecucion(String estadoEjecucion) {
        this.estadoEjecucion = estadoEjecucion;
    }

    public AppProcesoLog estadoEjecucion(String estadoEjecucion) {
        setEstadoEjecucion(estadoEjecucion);
        return this;
    }
    // -- [descripcionEstadoEjecucion] ------------------------

    @NotEmpty
    @Size(max = 4000)
    @Column(name = "descripcion_estado_ejecucion", nullable = false, length = 4000)
    public String getDescripcionEstadoEjecucion() {
        return descripcionEstadoEjecucion;
    }

    public void setDescripcionEstadoEjecucion(String descripcionEstadoEjecucion) {
        this.descripcionEstadoEjecucion = descripcionEstadoEjecucion;
    }

    public AppProcesoLog descripcionEstadoEjecucion(String descripcionEstadoEjecucion) {
        setDescripcionEstadoEjecucion(descripcionEstadoEjecucion);
        return this;
    }

    @NotEmpty
    @Size(max = 4000)
    @Column(name = "ancara", nullable = false, length = 4000)
    public String getAncara() {
        return ancara;
    }

    public void setAncara(String ancara) {
        this.ancara = ancara;
    }

    public AppProcesoLog ancara(String ancara) {
        setAncara(ancara);
        return this;
    }
    // -- [claseProgramacion] ------------------------

    @NotEmpty
    @Size(max = 100)
    @Column(name = "clase_programacion", nullable = false, length = 100)
    public String getClaseProgramacion() {
        return claseProgramacion;
    }

    public void setClaseProgramacion(String claseProgramacion) {
        this.claseProgramacion = claseProgramacion;
    }

    public AppProcesoLog claseProgramacion(String claseProgramacion) {
        setClaseProgramacion(claseProgramacion);
        return this;
    }
    // -- [metodoProgramacion] ------------------------

    @NotEmpty
    @Size(max = 100)
    @Column(name = "metodo_programacion", nullable = false, length = 100)
    public String getMetodoProgramacion() {
        return metodoProgramacion;
    }

    public void setMetodoProgramacion(String metodoProgramacion) {
        this.metodoProgramacion = metodoProgramacion;
    }

    public AppProcesoLog metodoProgramacion(String metodoProgramacion) {
        setMetodoProgramacion(metodoProgramacion);
        return this;
    }
    // -- [parametroEntrada] ------------------------

    @Size(max = 4000)
    @Column(name = "parametro_entrada", length = 4000)
    public String getParametroEntrada() {
        return parametroEntrada;
    }

    public void setParametroEntrada(String parametroEntrada) {
        this.parametroEntrada = parametroEntrada;
    }

    public AppProcesoLog parametroEntrada(String parametroEntrada) {
        setParametroEntrada(parametroEntrada);
        return this;
    }
    // -- [resultadoSalida] ------------------------

    @Size(max = 4000)
    @Column(name = "resultado_salida", length = 4000)
    public String getResultadoSalida() {
        return resultadoSalida;
    }

    public void setResultadoSalida(String resultadoSalida) {
        this.resultadoSalida = resultadoSalida;
    }

    public AppProcesoLog resultadoSalida(String resultadoSalida) {
        setResultadoSalida(resultadoSalida);
        return this;
    }
    // -- [usuario] ------------------------

    @NotEmpty
    @Size(max = 100)
    @Column(name = "usuario", nullable = false, length = 100)
    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public AppProcesoLog usuario(String usuario) {
        setUsuario(usuario);
        return this;
    }
    // -- [duracionMs] ------------------------

    @Digits(integer = 18, fraction = 0)
    @NotNull
    @Column(name = "duracion_ms", nullable = false, precision = 18)
    public Long getDuracionMs() {
        return duracionMs;
    }

    public void setDuracionMs(Long duracionMs) {
        this.duracionMs = duracionMs;
    }

    public AppProcesoLog duracionMs(Long duracionMs) {
        setDuracionMs(duracionMs);
        return this;
    }

    /**
     * Apply the default values.
     */
    public AppProcesoLog withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof AppProcesoLog && hashCode() == other.hashCode());
    }



    /**
     * Construct a readable string representation for this AppProcesoLog instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return "AppProcesoLog{" +
                "id=" + id +
                ", fechaInicioEjecucion=" + fechaInicioEjecucion +
                ", fechaFinEjecucion=" + fechaFinEjecucion +
                ", estadoEjecucion='" + estadoEjecucion + '\'' +
                ", descripcionEstadoEjecucion='" + descripcionEstadoEjecucion + '\'' +
                ", claseProgramacion='" + claseProgramacion + '\'' +
                ", metodoProgramacion='" + metodoProgramacion + '\'' +
                ", parametroEntrada='" + parametroEntrada + '\'' +
                ", resultadoSalida='" + resultadoSalida + '\'' +
                ", usuario='" + usuario + '\'' +
                ", duracionMs=" + duracionMs +
                ", ancara='" + ancara + '\'' +
                '}';
    }
}