-- /* CAMBIOS ADICIONALES PARA SILVESTRE EN BASE AL BACKEND MIGRADO */

-- /* UPDATE SEQUENCE */
ALTER SEQUENCE SEQ_PREGUNTA_INFORMACION RESTART WITH 1000;
ALTER SEQUENCE BANCO_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE TIPO_COMPROBANTE_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE MONEDA_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE TIPO_PROVEEDOR_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE LINEA_COMERCIAL_ID_SEQ RESTART WITH 1000;

ALTER SEQUENCE SEQ_PROVEEDOR_ADJUNTO_SUNAT RESTART WITH 1000;
ALTER SEQUENCE PROVEEDOR_CANAL_CONTACTO_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE PROVEEDOR_CATALOGO_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE SEQ_PROVEEDOR_CLIENTE RESTART WITH 1000;
ALTER SEQUENCE PROVEEDOR_CUENTA_BANCARIA_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE PROVEEDOR_EVALUACION_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE SEQ_PROVEEDOR_FUNCIONARIO RESTART WITH 1000;
ALTER SEQUENCE PROVEEDOR_HOMOLOGACION_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE SEQ_PROVEEDOR_INSTALACION RESTART WITH 1000;
ALTER SEQUENCE PROVEEDOR_LINEA_COMERCIAL_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE SEQ_PROVEEDOR_PERMISO RESTART WITH 1000;
ALTER SEQUENCE SEQ_PROVEEDOR_PREGUNTA_INFORMACION RESTART WITH 1000;
ALTER SEQUENCE PROVEEDOR_PRODUCTO_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE PROVEEDOR_SECTOR_TRABAJO_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE PROVEEDOR_TIPO_RETENCION_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE PROVEEDOR_ID_SEQ RESTART WITH 1000;


ALTER SEQUENCE SEQ_PRE_REGISTRO_LINEA_COMERCIAL RESTART WITH 1000;
ALTER SEQUENCE PRE_REGISTRO_PROVEEDOR_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE HOMOLOGACION_RESPUESTA_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE HOMOLOGACION_ID_SEQ RESTART WITH 1000;

ALTER SEQUENCE SEQ_USUARIO_LINEA_COMERCIAL RESTART WITH 1000;
ALTER SEQUENCE USUARIO_ID_SEQ RESTART WITH 1000;

-- /* PUBLICACION DOCUMENTOS */
ALTER SEQUENCE ORDEN_COMPRA_DETALLE_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE ORDEN_COMPRA_ID_SEQ RESTART WITH 1000;

ALTER SEQUENCE UNIDAD_MEDIDA_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE BIEN_SERVICIO_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE CENTRO_ALMACEN_ID_SEQ RESTART WITH 1000;

ALTER SEQUENCE DOCUMENTO_ACEPTACION_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE DOCUMENTO_ACEPTACION_DETALLE_ID_SEQ RESTART WITH 1000;

ALTER SEQUENCE PREFACTURA_ID_SEQ RESTART WITH 1000;

-- /* LICITACIONES */
ALTER SEQUENCE CONDICION_LIC_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE CONDICION_LIC_RESPUESTA_ID_SEQ RESTART WITH 1000;

ALTER SEQUENCE CCOMPARATIVO_ADJUDICADO_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE SEQ_CCOMPARATIVO_PROVEEDOR RESTART WITH 1000;
ALTER SEQUENCE CCOMPARATIVO_ID_SEQ RESTART WITH 1000;

ALTER SEQUENCE SEQ_LICITACION_PROVEEDOR_TIPO_CUESTIONARIO RESTART WITH 1000;
ALTER SEQUENCE SEQ_LICITACION_PROVEEDOR_RENEGOCIACION RESTART WITH 1000;
ALTER SEQUENCE SEQ_LICITACION_PROVEEDOR_PREGUNTA RESTART WITH 1000;
ALTER SEQUENCE SEQ_LICITACION_PROVEEDOR_DETALLE_EVALUACION RESTART WITH 1000;

ALTER SEQUENCE SEQ_COTIZACION_CAMPO_RESPUESTA_RECHAZADA RESTART WITH 1000;
ALTER SEQUENCE SEQ_COTIZACION_ADJUNTO_RECHAZADA RESTART WITH 1000;
ALTER SEQUENCE COTIZACION_ADJUNTO_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE GRUPO_CONDICION_LIC_RESPUESTA_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE LICITACION_GRUPO_CONDICION_LIC_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE SEQ_LICITACION_SUBETAPA RESTART WITH 1000;
ALTER SEQUENCE SEQ_LICITACION_ADJUNTO_RESPUESTA RESTART WITH 1000;
ALTER SEQUENCE LICITACION_ADJUNTO_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE SEQ_COTIZACION_DETALLE_RECHAZADA RESTART WITH 1000;
ALTER SEQUENCE COTIZACION_DETALLE_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE COTIZACION_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE SEQ_COTIZACION_RECHAZADA RESTART WITH 1000;
ALTER SEQUENCE CONTROL_CAMBIO_CAMPO_ID_SEQ RESTART WITH 1000;

ALTER SEQUENCE LICITACION_CONTROL_CAMBIO_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE LICITACION_DETALLE_ID_SEQ RESTART WITH 1000;
ALTER SEQUENCE LICITACION_ID_SEQ RESTART WITH 1000;

LICITACION_PROVEEDOR -- no aplica seq
COTIZACION_CAMPO_RESPUESTA -- no aplica seq