CREATE PROCEDURE SP_CREATE_OC_FROM_ANULADO(
	p_numero_orden_comra		NVARCHAR(10),
	p_fecha						DATE
) AS
BEGIN

	DECLARE v_current_id_oc	integer := 0;
	DECLARE v_seq integer := 0;
	DECLARE v_seq_detalle	integer := 0;

	SELECT ID_ORDEN_COMPRA INTO v_current_id_oc FROM ORDEN_COMPRA WHERE NUMERO_ORDEN_COMPRA = p_numero_orden_comra AND IS_ACTIVE = '1';
	SELECT ORDEN_COMPRA_ID_SEQ.nextval INTO v_seq FROM dummy;
	SELECT ORDEN_COMPRA_DETALLE_ID_SEQ.nextval INTO v_seq_detalle FROM dummy;

	/* Orden de Compra */
	INSERT INTO ORDEN_COMPRA
	(ID_ORDEN_COMPRA, AUTORIZADOR_FECHA_LIBERACION, CLASE_ORDEN_COMPRA, CODIGO_CLASE_ORDEN_COMPRA, CODIGO_MONEDA, COMPRADOR_NOMBRE, COMPRADOR_USUARIO_SAP,
	CONDICION_PAGO, CONDICION_PAGO_DESC, ESTADO_SAP, FECHA_APROBACION, FECHA_ENTREGA, FECHA_MODIFICACION, FECHA_PUBLICACION, FECHA_REGISTRO, FECHA_VISUALIZACION, HORA_MODIFICACION,
	ID_ESTADO_ORDEN_COMPRA, ID_TIPO_ORDEN_COMPRA, INDICADOR_CONTRATO_MARCO, IS_ACTIVE, LUGAR_ENTREGA, MOTIVO_RECHAZO, NUMERO_ORDEN_COMPRA, PROVEEDOR_CODIGO_SAP,
	PROVEEDOR_RAZON_SOCIAL, PROVEEDOR_RUC, SOCIEDAD, TOTAL, ULTIMO_LIBERADOR_USUARIO_SAP, VERSION, ID_EMPRESA, NO_REGISTRO, DCTO, SUBTOTAL, IMPUESTOS, ID_PAGO, ID_AGENDA_DIRECCION,
	ID_AGENDA_DIRECCION2, OBSERVACIONES, NOTAS_RECEPCION, FECHA_VIGENCIA, FECHA_ANULACION)
	SELECT v_seq, AUTORIZADOR_FECHA_LIBERACION, CLASE_ORDEN_COMPRA, CODIGO_CLASE_ORDEN_COMPRA, CODIGO_MONEDA, COMPRADOR_NOMBRE, COMPRADOR_USUARIO_SAP,
	CONDICION_PAGO, CONDICION_PAGO_DESC, 'L', FECHA_APROBACION, FECHA_ENTREGA, UTCTOLOCAL(now(), 'EST'), p_fecha, FECHA_REGISTRO, FECHA_VISUALIZACION, HORA_MODIFICACION,
	ID_ESTADO_ORDEN_COMPRA, ID_TIPO_ORDEN_COMPRA, INDICADOR_CONTRATO_MARCO, '1', LUGAR_ENTREGA, MOTIVO_RECHAZO, NUMERO_ORDEN_COMPRA, PROVEEDOR_CODIGO_SAP,
	PROVEEDOR_RAZON_SOCIAL, PROVEEDOR_RUC, SOCIEDAD, TOTAL, ULTIMO_LIBERADOR_USUARIO_SAP, 1, ID_EMPRESA, NO_REGISTRO, DCTO, SUBTOTAL, IMPUESTOS, ID_PAGO, ID_AGENDA_DIRECCION,
	ID_AGENDA_DIRECCION2, OBSERVACIONES, NOTAS_RECEPCION, FECHA_VIGENCIA, FECHA_ANULACION FROM ORDEN_COMPRA
	WHERE NUMERO_ORDEN_COMPRA = p_numero_orden_comra AND IS_ACTIVE = '1';

	/* Orden de Compra Detalle */
	INSERT INTO ORDEN_COMPRA_DETALLE
	(ID_ORDEN_COMPRA_DETALLE, CANTIDAD, CODIGO_SAP_ALMACEN, CODIGO_SAP_BIEN_SERVICIO, CODIGO_SAP_CENTRO, DENOMINACION_ALMACEN, DENOMINACION_CENTRO, DESCRIPCION_BIEN_SERVICIO,
	DIRECCION_CENTRO, FECHA_ENTREGA, ID_ORDEN_COMPRA, INDICADOR_IMPUESTO, NUMERO_ORDEN_COMPRA, POSICION, PRECIO_TOTAL, PRECIO_UNITARIO, TIPO_POSICION, UNIDAD_MEDIDA_BIEN_SERVICIO,
	ID_AMARRE, ID_AMARRE_SC, OP_SOLICITUD_COMPRA, CODIGO_PRODUCTO, KARDEX, DESCRIPCION_UNIDAD_MEDIDA, OBSERVACIONES)
	SELECT ORDEN_COMPRA_DETALLE_ID_SEQ.nextval, CANTIDAD, CODIGO_SAP_ALMACEN, CODIGO_SAP_BIEN_SERVICIO, CODIGO_SAP_CENTRO, DENOMINACION_ALMACEN, DENOMINACION_CENTRO, DESCRIPCION_BIEN_SERVICIO,
	DIRECCION_CENTRO, FECHA_ENTREGA, v_seq, INDICADOR_IMPUESTO, NUMERO_ORDEN_COMPRA, POSICION, PRECIO_TOTAL, PRECIO_UNITARIO, TIPO_POSICION, UNIDAD_MEDIDA_BIEN_SERVICIO,
	ID_AMARRE, ID_AMARRE_SC, OP_SOLICITUD_COMPRA, CODIGO_PRODUCTO, KARDEX, DESCRIPCION_UNIDAD_MEDIDA, OBSERVACIONES
	FROM ORDEN_COMPRA_DETALLE WHERE ID_ORDEN_COMPRA = v_current_id_oc AND NUMERO_ORDEN_COMPRA = p_numero_orden_comra /*NOT IN (40440, 40449, 40438, 40446)*/;


	-- Cambiar esstado a anulado la anterior OC
	UPDATE ORDEN_COMPRA SET ID_ESTADO_ORDEN_COMPRA = 5, ESTADO_SAP = 'A', FECHA_ANULACION = p_fecha WHERE ID_ORDEN_COMPRA = v_current_id_oc;

END;

-- CALL SP_CREATE_OC_FROM_ANULADO('23956', '2021-10-12');